
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Patrick
 */
public class HomeUserS extends javax.swing.JFrame {

    JpanelLoaderMain jpload = new JpanelLoaderMain();

    /**
     * Creates new form Home
     */
    public HomeUserS() {
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Image logo = new ImageIcon(this.getClass().getResource("/Logo.png")).getImage();
        this.setIconImage(logo);

        ItemM itemUser = new ItemM();
        jpload.jPanelLoader(MainFrame, itemUser);
        this.customerFrame.setForeground(Color.GREEN);

        User.setText("Welcome Back " + Login.Username.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customerFrame = new javax.swing.JButton();
        saleFrame = new javax.swing.JButton();
        pettyFrame = new javax.swing.JButton();
        stockFrame = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        creditorFrame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MainFrame = new javax.swing.JPanel();
        User = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELECTRONIC BILLING MACHINE");

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        customerFrame.setBackground(new java.awt.Color(0, 51, 0));
        customerFrame.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        customerFrame.setForeground(new java.awt.Color(255, 255, 255));
        customerFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/name-tag.png"))); // NOI18N
        customerFrame.setText("Customer");
        customerFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFrameActionPerformed(evt);
            }
        });

        saleFrame.setBackground(new java.awt.Color(0, 51, 0));
        saleFrame.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saleFrame.setForeground(new java.awt.Color(255, 255, 255));
        saleFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sale-tag.png"))); // NOI18N
        saleFrame.setText("Sales");
        saleFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleFrameActionPerformed(evt);
            }
        });

        pettyFrame.setBackground(new java.awt.Color(0, 51, 0));
        pettyFrame.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        pettyFrame.setForeground(new java.awt.Color(255, 255, 255));
        pettyFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/money.png"))); // NOI18N
        pettyFrame.setText("Petty Cash");
        pettyFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pettyFrameActionPerformed(evt);
            }
        });

        stockFrame.setBackground(new java.awt.Color(0, 51, 0));
        stockFrame.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        stockFrame.setForeground(new java.awt.Color(255, 255, 255));
        stockFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/packages.png"))); // NOI18N
        stockFrame.setText("Stock");
        stockFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockFrameActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 51, 0));
        Logout.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(204, 0, 0));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/power.png"))); // NOI18N
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        creditorFrame.setBackground(new java.awt.Color(0, 51, 0));
        creditorFrame.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        creditorFrame.setForeground(new java.awt.Color(255, 255, 255));
        creditorFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/creditor.png"))); // NOI18N
        creditorFrame.setText("Creditor");
        creditorFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditorFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saleFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditorFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pettyFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(Logout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerFrame)
                    .addComponent(saleFrame)
                    .addComponent(pettyFrame)
                    .addComponent(stockFrame)
                    .addComponent(Logout)
                    .addComponent(creditorFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dot.png"))); // NOI18N
        jLabel1.setText("Environment");

        javax.swing.GroupLayout MainFrameLayout = new javax.swing.GroupLayout(MainFrame);
        MainFrame.setLayout(MainFrameLayout);
        MainFrameLayout.setHorizontalGroup(
            MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MainFrameLayout.setVerticalGroup(
            MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        User.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        User.setForeground(new java.awt.Color(51, 153, 0));
        User.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        User.setText("jLabel2");
        User.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(User))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFrameActionPerformed
        // TODO add your handling code here:

        CustomerM customerUser = new CustomerM();
        jpload.jPanelLoader(MainFrame, customerUser);
        this.customerFrame.setForeground(Color.GREEN);
        this.saleFrame.setForeground(Color.WHITE);
        this.pettyFrame.setForeground(Color.WHITE);
        this.stockFrame.setForeground(Color.WHITE);
        this.creditorFrame.setForeground(Color.WHITE);

    }//GEN-LAST:event_customerFrameActionPerformed

    private void saleFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleFrameActionPerformed
        // TODO add your handling code here:

        SaleUserS SaleUser = new SaleUserS();
        jpload.jPanelLoader(MainFrame, SaleUser);
        this.saleFrame.setForeground(Color.GREEN);
        this.customerFrame.setForeground(Color.WHITE);
        this.pettyFrame.setForeground(Color.WHITE);
        this.stockFrame.setForeground(Color.WHITE);
        this.creditorFrame.setForeground(Color.WHITE);

    }//GEN-LAST:event_saleFrameActionPerformed

    private void stockFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockFrameActionPerformed
        // TODO add your handling code here:

        StockUserS StockUser = new StockUserS();
        jpload.jPanelLoader(MainFrame, StockUser);
        this.stockFrame.setForeground(Color.GREEN);
        this.customerFrame.setForeground(Color.WHITE);
        this.saleFrame.setForeground(Color.WHITE);
        this.pettyFrame.setForeground(Color.WHITE);
        this.creditorFrame.setForeground(Color.WHITE);

    }//GEN-LAST:event_stockFrameActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:

        new Login().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LogoutActionPerformed

    private void creditorFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditorFrameActionPerformed
        // TODO add your handling code here:

        Credit Creditor = new Credit();
        jpload.jPanelLoader(MainFrame, Creditor);
        this.creditorFrame.setForeground(Color.GREEN);
        this.customerFrame.setForeground(Color.WHITE);
        this.saleFrame.setForeground(Color.WHITE);
        this.pettyFrame.setForeground(Color.WHITE);
        this.stockFrame.setForeground(Color.WHITE);
    }//GEN-LAST:event_creditorFrameActionPerformed

    private void pettyFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pettyFrameActionPerformed
        // TODO add your handling code here:

        PettyCash PettyUser = new PettyCash();
        jpload.jPanelLoader(MainFrame, PettyUser);
        this.pettyFrame.setForeground(Color.GREEN);
        this.customerFrame.setForeground(Color.WHITE);
        this.saleFrame.setForeground(Color.WHITE);
        this.stockFrame.setForeground(Color.WHITE);
        this.creditorFrame.setForeground(Color.WHITE);
    }//GEN-LAST:event_pettyFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUserS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUserS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUserS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUserS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ValidateForm.waitForInternetConnection();
                new HomeUserS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainFrame;
    private javax.swing.JLabel User;
    private javax.swing.JButton creditorFrame;
    private javax.swing.JButton customerFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pettyFrame;
    private javax.swing.JButton saleFrame;
    private javax.swing.JButton stockFrame;
    // End of variables declaration//GEN-END:variables
}
